name: Push

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  benchmark:
    name: Benchmark `ReadDir` vs `Readdir`
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - uses: actions/checkout@v3
      - run: go test -bench=.
